export default {
  SEARCH_ARTIST : 'SEARCH_ARTIST',
  SEARCH_ALBUMNS: 'SEARCH_ALBUMNS',
  USER_LOGGED: 'USER_LOGGED',
  ALBUMNS_BY_ID: 'ALBUMNS_BY_ID',
  TRACKS_BY_ID: 'TRACKS_BY_ID',
  SET_FAVORITE: 'SET_FAVORITE'
}